### ISSUE TITLE
Install documate

### ISSUE THREAD

**Issue by ubugeeei** [chibivue-land/chibivue#272]
@documate/vu
https://github.com/AirCodeLabs/documate
https://documate.site/reference/documate-vue

**Comment by Yordan-Ramchev** [comment]
May I assist with that :)

**Comment by Ubugeeei** [comment]
OK, if you need anything, please make a request here. ;D

**Comment by Yordan-Ramchev** [comment]
https://twitter.com/aircode_io/status/1766030186661949555 - I don't think aircode hosting is an option
